name: Documentation Deployment

on:
  push:
    branches:
      - Development
      - Beta
      - main

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/Development'
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Dev
        run: echo "Deploying documentation to Dev"

  deploy-beta:
    if: github.ref == 'refs/heads/Beta'
    runs-on: ubuntu-latest
    environment: Beta

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Beta
        run: echo "Deploying documentation to Beta"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Production
        run: echo "Deploying documentation to Production"
